# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2
jobs:
  build:
    working_directory: ~/sparql-loader
    docker:
      - image: circleci/python:3.6.4  # primary container
    steps:
      - checkout # checkout source code to the working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install --upgrade pip
            # pip3 install -r requirements.txt
            python -m venv env
            source env/bin/activate # load our virtual env
            pip install rdflib
            pip install boto3
            pip install rdflib-sparql
            pip install honeybadger
            pip install pytest
            pytest -k unit # only run unit tests at this stage
